title: louisb0
description: Articles on systems programming.
author: Louis Baragwanath
url: https://louis.co.nz
lang: en
goat_counter: louisb0

theme_config:
  appearance: "light"
  back_home_text: "back"
  date_format: "%Y-%m-%d"
  show_description: false
  lowercase_titles: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .devenv
  - devenv.nix
  - devenv.yaml
  - devenv.lock
