title: louis
author: Louis Baragwanath
email: na@gmail.com
url: "https://louisb0.github.io"
baseurl: "/louis.co.nz"
description: >
  A blog.

theme_config:
  appearance: "light"
  back_home_text: "back"
  date_format: "%Y-%m-%d"
  show_description: false
  lowercase_titles: true

permalink: /:year/:month/:day/:title:output_ext

destination: ../docs

plugins:
  - jekyll-seo-tag
