title: louisb0
description: A series of notes on systems programming.
url: https://louis.co.nz

author: Louis Baragwanath
favicon: /assets/img/favicon.ico
goat_counter: louisb0
lang: en

theme_config:
  appearance: "light"
  back_home_text: "back"
  date_format: "%Y-%m-%d"
  show_description: true
  lowercase_titles: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - CNAME
  - .devenv
  - devenv.nix
  - devenv.yaml
  - devenv.lock

jekyll-seo-tag:
  json_ld: false
